### PR TITLE
Release 1 point 0

### PR DESCRIPTION
**Pull request by h-lame**
We tidy up the readme and changelog a wee bit and call it 1.0.0.

### CODE REVIEW

**Review by elenatanasoiu — APPROVED** [review]

**Comment by fofr** [comment]
Should this repo make it clear what a BOM is?

**Comment by h-lame** [comment]
@fofr I thought that linking to the wikipedia page definition of BOM might be enough (we do something similar for SRI) but the link isn't on the first use of BOM in the readme which seems like a mistake, so I'll change where the link lives.  Would that be enough, or should we make it clearer with a short definition of our own?

**Comment by fofr** [comment]
I think it should be clearer. I think it's the first question to answer in the readme.

**Comment by h-lame** [comment]
Attempted to make the readme clearer in https://github.com/alphagov/asset_bom_removal-rails/pull/5

**Pull request merged**
