### PR TITLE
Remove BOM with a custom sass processor

### PR DESCRIPTION
**Pull request by h-lame**
For: https://trello.com/c/UcJJBH0k/183-investigate-bom-issue-with-asset-compilation

Instead of processing the CSS files after they have been through the
sprockets process (see #2 for why this didn't work) we instead do it
during the process by using our own sass compressor.  This 
compressor extends the default one and removes the BOM from the
compressed CSS if it is present.

TODO: check that our compressor doesn't miss out on any sass config the
app might set - perhaps we want to grab the existing sass compressor
instance and wrap it, rather than extending the class.

### CODE REVIEW

**Comment by h-lame** [comment]
This has been tested on integration with the [`add-sri-again` branch of government frontend](https://github.com/alphagov/government-frontend/tree/add-sri-again) and the assets are correctly rendered by Firefox < 52.

**Comment by h-lame** [comment]
It's also been tested in dev with [static](https://github.com/alphagov/static) to make sure that it can still compile the assets too (government-frontend is a rails 5 app, static is a rails 4.2 app).  As it turns out none of the static stylesheets generate a BOM anyway (because there's no non-ascii characters in the css), so we had to add one.  Everything seemed to work when we did, which is nice.

Note: we *may* need to force a precompile when we deploy to make sure that the assets are all freshly compiled.

**Comment by h-lame** [comment]
ps.  Thanks to @pixeltrix for the advice on how to hook directly into the asset-pipeline

**Comment by tomnatt** [comment]
Like the approach. One thought - you're assuming (or at least only making changes for) UTF-8. This probably makes sense, but it would be good to specify in the README for future reference. Also, not sure if you're looking for a full review here but don't forget to update the `gemspec` file.

**Comment by h-lame** [comment]
Ah, yes, I should be more explicit about UTF-8, particularly as Sass only adds the BOM when it has to output UTF-8 characters in the CSS. I'll update the README accordingly.  When you say update the `gemspec` what do you think I'm missing?

**Comment by tomnatt** [comment]
I meant the description, but on second reading it's fine. Ignore me 😄

**Comment by h-lame** [comment]
@tomnatt - cool; thanks for taking a look!

**Review by elenatanasoiu — APPROVED** [review]

**Pull request merged**
